import ListBet from "./components/ListBet/ListBet"
import Bet from "./components/Bet/Bet.jsx"
import Connecter from "./components/Connecter/Connecter";
import MyP2PBets from "./components/MyP2PBets/MyP2PBets";
import DecentraBet from "./components/DecentraBet/DecentraBet";
import Classement from "./components/Classement/Classement";
import MyBets from "./components/MyBets/MyBets";
import Account from "./components/Account/Account";
import BetMaker from "./components/betMaker/betMaker";
import ComingSoon from "./components/ComingSoon/ComingSoon";
import LandingComponent from "./components/LandingComponent/LandingComponent"
import USDTGetter from "./components/USDTGetter/USDTGetter"
import GetGains from "./components/GetGains/GetGains";
import BetterMobile from "./components/BetterMobile/BetterMobile";
import BetterBottomRight from "./components/BetterBottomRight/BetterBottomRight";
import Base from "./components/Base/Base"
import NotificationsMobile from "./components/NotificationsMobile/NotificationsMobile"
import LeagueBet from "./components/LeagueBet/LeagueBet.js";
export {LeagueBet, ListBet, Bet, Connecter, MyP2PBets, DecentraBet, Classement, MyBets, Account, BetMaker, ComingSoon, LandingComponent, USDTGetter, GetGains, BetterMobile, BetterBottomRight, Base, NotificationsMobile }