import homeImage from './assets/home.png'
import titleImage from './assets/bettingCrocTitle.png'
import basketBallImage from './assets/basketball.png'
import footballImage from './assets/football.png'
import financeImage from './assets/finance.png'
import tennisImage from './assets/tennis.png'
import accountImage from './assets/account.png'
import hamburgerImage from './assets/hamburger.png'
import hamburgerWhiteImage from "./assets/hamburgerWhite.png"
import accountImageWhite from './assets/accountWhite.png'
import sunImage from "./assets/sunDark.png"
import moonImage from "./assets/moon.png"
import sunYellowImage from "./assets/sunYellow.png"
import moonYellowImage from "./assets/moonYellow.png"
import closeImage from "./assets/close.png"
import sportsInactive from "./assets/sportsInactive.png"
import sportsLight from "./assets/sportsLight.png"
import sportsDark from "./assets/sportsDark.png"
import rankingInactive from "./assets/rankingInactive.png"
import rankingLight from "./assets/rankingLight.png"
import rankingDark from "./assets/rankingDark.png"
import decentraBetDark from "./assets/decentraBetDark.png"
import decentraBetLight from "./assets/decentraBetLight.png"
import decentraBetInactive from "./assets/decentraBetInactive.png"
import notificationsInactive from "./assets/notificationsInactive.png"
import notificationsLight from "./assets/notificationsLight.png"
import notificationsDark from "./assets/notificationsDark.png"
import walletDark from "./assets/walletDark.png"
import walletLight from "./assets/walletLight.png"
import crocodileRight from './assets/crocodileRight.png'
import tutorialsDark from './assets/tutorialsDark.png'
import tutorialsLight from './assets/tutorialsLight.png'
import rankingLandingLight from './assets/rankingLandingLight.png'
import rankingLandingDark from './assets/rankingLandingDark.png'
import helpDark from './assets/helpDark.png'
import helpLight from './assets/helpLight.png'
import landingBackground from './assets/landingBackground.jpg'
import lakersJersey from "./assets/jerseys/lakers.png"
import celticsJersey from "./assets/jerseys/celtics.png"
import sportsWhite from "./assets/sportsWhite.png"
import decentraBetWhite from "./assets/decentraBetWhite.png"

export { decentraBetWhite, sportsWhite, celticsJersey, lakersJersey, landingBackground, helpDark, helpLight, tutorialsDark, tutorialsLight, rankingLandingLight, rankingLandingDark, walletDark, crocodileRight, walletLight, closeImage, homeImage, titleImage, basketBallImage, footballImage, financeImage, tennisImage, accountImage, hamburgerImage, hamburgerWhiteImage, accountImageWhite, sunImage, moonImage, sunYellowImage, moonYellowImage, sportsInactive, sportsLight, sportsDark, rankingInactive, rankingDark, rankingLight, decentraBetDark, decentraBetInactive, decentraBetLight, notificationsDark, notificationsInactive, notificationsLight }